version: 2.1

jobs:
  build:
    docker:
      - image: golang:latest

    steps:
      - checkout:
          path: /home/circleci/project/tdo
      #- run: go test

      - run:
          name: Print directory structure
          command: ls -R /home/circleci/project

      - run:
          name: show current directory
          command: cd

      - run: 
          name: Compile the binary
          command: cd tdo/agent && go build -o tdo_agent .

workflows:
  version: 2
  build:
    jobs:
      - build
