version: 2.1

jobs:
  build:
    docker:
      - image: golang:latest

    working_directory: /home/circleci/project/agent

    steps:
      - checkout
      #- run: go test

      - run:
          name: Print directory structure
          command: ls -R /home/circleci/project

      - run: 
          name: Compile the binary
          command: go build -o tdo_agent .

workflows:
  version: 2
  build:
    jobs:
      - build
