version: 2.1

jobs:
  build:
    docker:
      - image: golang:latest

    steps:
      - checkout

      - run:
          name: show current directory
          command: pwd && ls -R

      #- run: go test

      #- run: 
      #    name: Compile the binary
      #    command: cd /home/circleci/project/tdo/agent && go build -o tdo_agent .

workflows:
  version: 2
  build:
    jobs:
      - build
