version: 2.1

jobs:
  build:
    machine: 
      image: ubuntu-2204:current

    steps:
      - checkout

      - run: 
          name: unit test
          command: cd agent && go test

      - run: 
          name: Compile the binary
          command: cd agent && ./build.sh

  freeradius_job:
    docker:
      - image: freeradius/freeradius-server:latest
    steps:
      - checkout
      #- run:
      #    name: Copy FreeRADIUS Config
      #    command: cp -r /path/to/your/freeradius/config/* /etc/freeradius/

      #- run:
      #    name: Restart FreeRADIUS
      #    command: service freeradius restart

      - run:
          name: check environment
          command: ip address && ss -unlp

workflows:
  version: 2
  build:
    jobs:
      - build
      - freeradius_job
