version: 2.1

jobs:
  build:
    docker:
      - image: cimg/golang@1.9.0

    steps:
      - checkout
      #- run: go test
      - run: agent/build.sh

workflows:
  version: 2
  build:
    jobs:
      - build
