version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      #- run:
      #    name: unit test
      #    command: cd agent && go test
      - run:
          name: Compile the binary
          command: cd agent && ./tests/build.sh && ls build
      - run:
          name: Modify client.conf file
          command: |
            export VM_IP=$(hostname --ip-address | grep -oP '\b(?:\d{1,3}\.){3}\d{1,3}\b')
            echo "VM_IP: $VM_IP" 
            tac agent/tests/clients.conf.good | awk -v ip="$VM_IP" '/ipaddr *=/ && !changed {sub(/ipaddr *=.*/, "ipaddr = " ip); changed=1} 1' | tac > agent/tests/clients.conf
      - run:
          name: Start FreeRADIUS Docker container
          command: docker run -d --name freeradius-container -v $(pwd)/agent/tests/clients.conf:/etc/freeradius/clients.conf -v $(pwd)/agent/tests/users:/etc/freeradius/users -p 1812:1812/udp freeradius/freeradius-server:latest
      #- run:
      #    name: Find Freeradius Configuration Files
      #    command: docker exec freeradius-container find /etc/ -type f -name 'users' -o -name 'clients.conf'
      - run:
          name: Print last 5 lines of clients.conf
          command: |
            docker exec freeradius-container ls -l /etc/freeradius/ && docker exec freeradius-container tail -n 5 /etc/freeradius/clients.conf
            docker exec freeradius-container tail -n 5 /etc/freeradius/users
      - run:
          name: Set FreeRADIUS IP address as environment variable
          command: echo "FREERADIUS_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' freeradius-container)" >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Start tdo agent
          command: pwd && ./agent/build/tdo_agent_linux_amd64 &
      - run:
          name: Run integration tests
          #command: docker exec -it freeradius-container radtest testuser testpassword localhost 0 testing123
          command: pwd && cd agent/tests && ./prepare_python.sh
      - run:
          name: Stop FreeRADIUS Docker container
          command: docker stop freeradius-container && docker rm freeradius-container

workflows:
  version: 2
  build:
    jobs:
      - build
