version: 2.1

jobs:
  build:
    machine: 
      image: ubuntu-2204:current

    steps:
      - checkout

      #- run:
      #    name: show current directory
      #    command: pwd && ls -R

      - run: 
          name: unit test
          command: cd agent && go test

      - run: 
          name: Compile the binary
          command: cd agent && ./build.sh

workflows:
  version: 2
  build:
    jobs:
      - build
