version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: unit test
          command: cd agent && go test
      - run:
          name: Compile the binary
          command: cd agent && ./build.sh
      - run:
          name: Modify client.conf file
          command: export VM_IP=$(ip addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}') && tac agent/tests/clients.conf.good | awk -v ip="$VM_IP" '/ipaddr *=/ && !changed {sub(/ipaddr *=.*/, "ipaddr = " ip); changed=1} 1' | tac > agent/tests/clients.conf
      - run:
          name: Start FreeRADIUS Docker container
          command: docker run -d --name freeradius-container -v agent/tests/clients.conf:/etc/freeradius/3.0/clients.conf -v agent/tests/users:/etc/freeradius/3.0/users -p 1812:1812/udp freeradius/freeradius-server:latest
      - run:
          name: Set FreeRADIUS IP address as environment variable
          command: echo "FREERADIUS_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' freeradius-container)" >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Run integration tests
          #command: cd agent && ./integration_tests.sh  # Replace with the actual command for your integration tests
          command: docker exec -it freeradius-container radtest testuser testpassword localhost 0 testing123
      - run:
          name: Stop FreeRADIUS Docker container
          command: docker stop freeradius-container && docker rm freeradius-container

workflows:
  version: 2
  build:
    jobs:
      - build
