version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.21

    steps:
      - checkout
      #- run: go test
      - run: agent/build.sh

workflows:
  version: 2
  build:
    jobs:
      - build
